### ISSUE TITLE
"%>>%" is already being used by the package pipeR

### ISSUE THREAD

**Issue by AndreMikulec** [markvanderloo/lumberjack#1]
is it possible to use a differently named pipe instead of "%>>%" Pehaps "%>L>%"

Pipe "%>>%" is already being used by the package pipeR.

https://renkun.me/rlist-tutorial/Getting-started/Quick-overview.html

**Comment by markvanderloo** [comment]
I didn't think of that as a problem, since I don't think people would use both operators in one script (you can just not `start_log()`). OTOH I see the point. Bit hard to revert now that its out there, but what if I add a synomym like `%L>%` . That way you can do

```r
library(lumberjack)
library(pipeR)
```
and `%>>%` will still be ```pipeR::`%>>%` ```?

**Comment by AndreMikulec** [comment]
Sounds like a great idea.
