### ISSUE TITLE
logging fails when tibble is supplied vs. data.frame

### ISSUE THREAD

**Issue by eafpres** [markvanderloo/lumberjack#4]
When an operation is performed that coerces the data into a tibble, the logging fails with errors.  In the below example, the error is:

> Error in `$<-.data.frame`(`*tmp*`, value, value = c("1", "2", "3", "4",  : 
  replacement has 10692 rows, data has 12

`
#
  library(lumberjack)
  rm(list = ls())
#
  train_data <- read.csv("train_original.csv", 
                         header = TRUE,
                         stringsAsFactors = FALSE)
  train_data <- train_data %>>%
    mutate(id = seq(1, nrow(train_data), 1)) %>%
#
# following ensures blanks are NA, but also coerces to tibble
#
    replace_with_na_all(condition = ~.x == "")
#
# doesn't work:
#
  train_data <- train_data %>>% 
    #as.data.frame() %>>%
    start_log(log = cellwise$new(key = "id")) %>>%
    impute_lm(Age ~ Fare + Pclass + Sex + Embarked) %>>%
    dump_log(stop = TRUE, file = "train_log.csv")
#
# works
#
  train_data <- train_data %>>% 
    as.data.frame() %>>%
    start_log(log = cellwise$new(key = "id")) %>>%
    impute_lm(Age ~ Fare + Pclass + Sex + Embarked) %>>%
    dump_log(stop = TRUE, file = "train_log.csv")`

**Comment by markvanderloo** [comment]
yep. That's a problem, also in the unpublished v. 0.3. Will have a look. But I must say that `dplyr` and the whole `tidyverse` is pretty aggressive in altering the data that is fed to it. I talked to one of the developers IRL as well as posting issues about it, and it is not going to change. Hopefully developers on the fringe of the tidyverse (like me) can work around it.

Here's a reproducible example that doesn't depend on `train_data` (`group_by` also turns a `data.frame` into a `tibble`).

```r
> iris$id <- seq_len(nrow(iris))
> out <- iris %>%
+   start_log(cellwise$new(key="id")) %>>%
+   group_by(Species) %>>%
+   mutate(ratio=Sepal.Length/Sepal.Width) %>>%
+   dump_log()
 Show Traceback
 
 Rerun with Debug
 Error in `$<-.data.frame`(`*tmp*`, value, value = c("5.1", "4.9", "4.7",  : 
  replacement has 750 rows, data has 5 
```

```r
> iris$id <- seq_len(nrow(iris))
> out <- iris %>%
+   start_log(cellwise$new(key="id")) %>>%
+ #  group_by(Species) %>>%
+   mutate(ratio=Sepal.Length/Sepal.Width) %>>%
+   dump_log()
Dumped a log at cellwise.csv
```

**Comment by eafpres** [comment]
Totally agree. Although tidyverse has merit, there are also things not to like

**Comment by markvanderloo** [comment]
I've almost fixed it. I stumbled upon this inconsistency:

```r
> class(group_by(iris, Species)[,"Sepal.Width",drop=TRUE])
[1] "tbl_df"     "tbl"        "data.frame"
> class(as_tibble(iris)[,"Sepal.Width",drop=TRUE])
[1] "numeric"
```

**Comment by markvanderloo** [comment]
Ok, package builds and works on my side. I would be grateful if you could give it a whirl as an extra check so I can upload it to CRAN next Friday.
Cheers for reporting!

**Comment by eafpres** [comment]
I'm having trouble installing from github; can you tell me what path I should be using in install_github("path")?

**Comment by markvanderloo** [comment]
woops, sorry. my repos generally don't support `install_github`. Putting `.Rd` files on GH pollutes my commit history since it is generated from Roxygen. I used to publish beta versions through `drat` but I somehow foobar'd my GH pages.

If you want I can set up a tar.gz download, or you can do this.

```
git clone https://github.com/markvanderloo/lumberjack
cd lumberjack
```
THen start R
```r
devtools::load_all('pkg')
```

**Comment by eafpres** [comment]
I confirm it works in both cases I reported.  Thanks for this!

**Comment by markvanderloo** [comment]
Thanks for reporting and testing! I will push the new version to Cran end of this week.
