### ISSUE TITLE
logging does not work with mutate()

### ISSUE THREAD

**Issue by eafpres** [markvanderloo/lumberjack#5]
Using mutate during logging generates errors.  For example, the following code generates the error:

> Error in dump_log(., stop = TRUE, file = "train_log.csv") : 
  attempt to apply non-function

`
#
  rm(list = ls())
#
  train_data <- read.csv("train_original.csv", 
                         header = TRUE,
                         stringsAsFactors = FALSE)
  train_data <- train_data %>>%
    mutate(id = seq(1, nrow(train_data), 1)) %>%
    replace_with_na_all(condition = ~.x == "")
#
# doesn't work:
#
  train_data <- train_data %>>% 
    as.data.frame() %>>%
    start_log(log = cellwise$new(key = "id")) %>>%
    mutate(MWC = character(length = nrow(train_data))) %>>%
    impute_lm(Age ~ Fare + Pclass + Sex + Embarked) %>>%
    dump_log(stop = TRUE, file = "train_log.csv")
#
# works:
#
  train_data <- train_data %>>% 
    as.data.frame() %>>%
    start_log(log = cellwise$new(key = "id")) %>>%
    # mutate(MWC = character(length = nrow(train_data))) %>>%
    impute_lm(Age ~ Fare + Pclass + Sex + Embarked) %>>%
    dump_log(stop = TRUE, file = "train_log.csv")`

**Comment by markvanderloo** [comment]
Thanks for reporting. It is related to [this issue](https://github.com/tidyverse/dplyr/issues/3558#issuecomment-387415423). It is solved in the development version of lumberjack, which I should have published weeks ago. I will push it to CRAN asap.

**Comment by eafpres** [comment]
Thanks!
